---
- name: Install required packages
  apt:
    name: "{{packages}}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3-ldap

- name: Install pip packages
  pip:
    name:
      - kubernetes

- name: Transfer openldap config values file
  template:
    src: values.yml
    dest: "/tmp/openldap_values.yml"
    mode: 0644

- name: Install openldap helm chart
  kubernetes.core.helm:
    release_name: "{{openldap_app_name}}"
    chart_ref: openldap-stack-ha
    chart_repo_url: https://jp-gouin.github.io/helm-openldap
    release_namespace: "{{openldap_namespace}}"
    create_namespace: true
    wait: yes
    values_files:
      - /tmp/openldap_values.yml
  become_user: "{{admin_user}}"

###################################################################################
# Export config values as facts for use in playbooks

- name: Get OpenLDAP service IP
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Service
    name: openldap
    namespace: "{{openldap_namespace}}"
  become_user: "{{admin_user}}"
  register: L_OPENLDAP_SERVICE_INFO

- name: Export variables
  set_fact:
    OPENLDAP_SERVICE_INFO: "{{L_OPENDLDAP_SERVICE_INFO}}"

