# Custom config values, see https://github.com/jp-gouin/helm-openldap/blob/master/values.yaml for reference
global:
  ldapDomain: {{openldap_domain}}
  adminPassword: {{openldap_admin_password}}
  configPassword: "{{openldap_admin_password}}"
replicaCount: {{openldap_replicas}}

service:
  type: NodePort
  ldapPortNodePort: {{openldap_nodeport}}

replication:
  enabled: false

persistence:
  size: 50Mi

phpldapadmin:
  enabled: false
