# Custom config values, see https://github.com/jp-gouin/helm-openldap/blob/master/values.yaml for reference
global:
  ldapDomain: "{{ldap_domain}}"
  adminPassword: "{{admin_password}}"

service:
  type: NodePort
  ldapPortNodePort: {{ldap_nodeport}}

replication:
  enabled: false

persistence:
  size: 50Mi

phpldapadmin:
  enabled: false
